language: go
go:
- 1.8
deploy:
  provider: gae
  keyfile: client-secret.json
  project: go-jawscout-cc
before_install:
- openssl aes-256-cbc -K $encrypted_a67d938c51e9_key -iv $encrypted_a67d938c51e9_iv
  -in client-secret.enc -out client-secret.json -d